### ISSUE TITLE
Add a small comment on reactions{} entry

### ISSUE THREAD

**Issue by blttkgl** [kahilah/ct2foam#1]
The reactions{} entry generated for the mechanism input files are supposed to be empty, since the reaction information is stored on libc_pyjac.so dynamic lib generated by pyJac.

I got some feedback from users that having no comments led them to think there was something wrong with ct2foam and that reaction information should be there.

So I propose putting a one-line comment explaining that the reaction information is stored in libc_pyjac.so file.

**Comment by kahilah** [comment]
Good proposal. 

Fix introduced in commit https://github.com/kahilah/ct2foam/commit/6cfb9bb4aa94ce14597b35f05e587367a2f9516b
