### ISSUE TITLE
cvxopt might need to be considered during the env installation 

### ISSUE THREAD

**Issue by mahgadalla** [kahilah/ct2foam#11]
Hi Heikki,

I noted in some local installations of CT2Foam that building of cvxopt fails due to the missing umfpack.h header. Snippet below:

gcc -pthread -B <ENV_PATH>/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I<PYTHON_INC_PATH>/python3.6m -c src/C/umfpack.c -o build/temp.linux-x86_64-3.6/src/C/umfpack.o
  src/C/umfpack.c:23:10: fatal error: umfpack.h: No such file or directory
     23 | #include "umfpack.h"
        |          ^~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cvxopt
Successfully built ct2foam
Failed to build cvxopt
ERROR: Could not build wheels for cvxopt, which is required to install pyproject.toml-based projects

Such an issue can be avoided by simply appending cvxopt to the list of additional packages, while creating the conda env. It would be useful if the respective line in README gets updated accordingly, i.e.

> conda create --name ct2foam_env --channel cantera cantera python=3.6 numpy scipy matplotlib cvxopt

**Comment by kahilah** [comment]
Thanks for reporting. I'm planning to update the build instructions soon anyway as Anaconda licensing changes are not anymore very suitable for many people so will consider this at the same time.

**Comment by kahilah** [comment]
Added to the readme for now.
