### ISSUE TITLE
repr() function prints out also data type which is inconvenient

### ISSUE THREAD

**Issue by mahgadalla** [kahilah/ct2foam#13]
Hi @kahilah,

The repr() function inside ct2foam/thermo_transport/foam_writer.py would print out data type as well "e.g. np.float64(..)" which is quite inconvenient when writing out mixture properties or else for OpenFOAM, and a user needs to manually remove them.

I'd suggest only replacing it with a simple str() to avoid this. The following line will do the job:

> sed -i 's/repr/str/g' ct2foam/thermo_transport/*

Regards,
Mahmoud

**Comment by kahilah** [comment]
Thanks for reporting. I agree with you 100%. Repr seems to be an old residue indeed. 

Out of curiosity, was this a problem only now after some update, or did you use some functionalities in other context?

I'll fix this later tonight.

**Comment by kahilah** [comment]
Fixed by commit https://github.com/kahilah/ct2foam/commit/984c268a751fc3545b610c0fd83a6e4dab007509

**Comment by mahgadalla** [comment]
Hey Heikki,

Thanks a lot for the prompt fix!

> Out of curiosity, was this a problem only now after some update, or did you use some functionalities in other context?

Just for the same context they were intended for, although probably the behavior of repr() did not change over time!
