### ISSUE TITLE
Different JANAF polynomials in chem_utils.c and thermo.foam

### ISSUE THREAD

**Issue by moreff** [kahilah/ct2foam#3]
ct2foam utility refits JANAF polynomials to get rid of possible discontinuities at `Tmid` of a polynomial.
The fitted polynomial goes to `thermo.foam` file, used by `thermophysicalProperties` module of OpenFOAM.
However, pyJac uses the original `.cti` file with original JANAF polynomials to generate `chem_utils.c`, which is then used in the chemistry solver. 
Thus, there is an inconsistency where different parts of the code use (probably slightly, but still) different thermal properties, which might lead to convergence/accuracy issues.

I would suggest using refitted polynomials everywhere. 
The first thing that comes to my mind is the creation of another file (eg. `mech_refitted.cti` or use `.yaml` format as an intermediate step and `cti2yaml`+`yaml2cti`) with updated JANAF polynomials, which then can be used with by pyJac

**Comment by kahilah** [comment]
Your description of the functionality is correct and indeed there is an inconsistency between pyjac internal routines and the OpenFOAM.

However, it is worth noting that in any operator splitting approach utilised in reactive CFD, your species and energy transport and their respective source terms can be independent. And that is true for e.g. the DLBFoam implementation, for which this utility is often utilised. As the pyJac routines are used to provide the source terms for the species net-production rates only, there is no real need to ensure 100% consistency between the fluid transport and the internal thermodynamics of the ODE solution. 

I tested this long time ago and in practice, the difference is mostly negligible and anyway overshadowed by e.g. error / noise coming from:
- first order operator splitting in CFD software (OpenFOAM)
- Sub-grid combustion model, which operates directly on species source terms.
- mixture averaging of thermodynamics in CFD software
- Finite accuracy of transport terms anyway (Numerical diffusion)

Personally, I have made a decision to utilise the original chemical mechanism thermodynamics data for the chemistry source term (=pyjac) as certain heavily reduced mechanisms have non-smooth, discontinuous thermo data baked into them during the mechanism optimisation process (Not the approach I'd go, but I have seen this happening...). However, I want to have smooth and similarly characterised data for OpenFoam from performance and transport robustness perspective.

If you have a case, in which the inconsistency really matters and you want absolute consistency, I would do exactly as you suggested, i.e. rewrite the cantera .cti/yaml file with new thermodata by using gas.write_yaml(). 

Also. I'm interested to hear if you have any example case showing drastic inconsistency, leading to convergence issues?
