### ISSUE TITLE
Minimum temperature limit

### ISSUE THREAD

**Issue by scramjetFoam** [kahilah/ct2foam#4]
Hi,

I noticed the  Minimum temperature of Tlow is 280.0K. Why designed it this way? Is there a way out of this? Because the lowest temperature in my mechanism file is 200K.

Regards

**Comment by kahilah** [comment]
Hi,

You are correct that by default the scripts result in Tlow=280. However, the codebase is not restricted to it, as you can see in class input parameters at https://github.com/kahilah/ct2foam/blob/a65f8cf5bdccdae00e4db44f31fdd6cf3f9e9fdc/ct2foam/thermo_transport/ct_properties.py#L5

When I was building this package, I set the default T range based on values most of my chemical mechanisms were configured. Furthermore, all my simulation cases were never reaching lower T values. 

To resolve the issue, you can make your own mech2foam.py script in which you replace add T=linspace(myTstart, myTend, 256)  into ct_properties.ctThermoTransport() declaration.

I'm also open to review a pull request on this topic. Or if you're not in a hurry, I can modify the existing script accordingly later this week.

**Comment by scramjetFoam** [comment]
Hi,

I'm not very good at programming, so I may have to wait for your modified version. I also have a suggestion as to whether Thigh can correspond to the value of the reaction species, whose value is unique at the moment, which is _**myTend**_.

Regards.

**Comment by kahilah** [comment]
ok, I'll make an update later this week and inform you here.

Regarding your suggestion, this tool is designed to be used with reaction mixtures in simulations in which any of the reaction species can be active. Hence, the user should consider what kind of temperature levels the overall simulation will experience and define the limits accordingly. In other words, if the simulation is going to have temperatures near 3000K, then the highest T value should be anyway defined commonly for all species, even though individual species may have higher end temperature available in e.g. literature.

**Comment by scramjetFoam** [comment]
Roger it. Thank you.

**Comment by kahilah** [comment]
`mech2foam `and `mix2foam `scripts support now `--Tlow` and `--Thigh` arguments for low and high polynomial temperature limits, respectively.

**Comment by scramjetFoam** [comment]
Thanks for your work.
