### ISSUE TITLE
pyjac still have the Temperature limit

### ISSUE THREAD

**Issue by scramjetFoam** [kahilah/ct2foam#7]
Hi, 

recently I used DLBfoam to study detonation problems. I noticed that the thermo.foam file generated with pyjac still has a temperature limit. Tlow = 280.0; Thigh = 3000.0; High temperatures are common in detonation problems, but this triggers a heat warning. 

Whether the temperature limit of pyjac can also be lifted.

Regards

**Comment by kahilah** [comment]
Hi,

pyjac files are generated by the `pyjac2foam.sh` script in which we call ct2foam fitting function https://github.com/kahilah/ct2foam/blob/09837b4c0a4a19e02fd21f0a0d0a74cb83285473/pyjac2foam/pyjac2foam.sh#L190

As you can see, there is no -Th argument prescribing the higher temperature limit as it is typically intended for rather standard cases.

You can add your own limit there but I'm not a fan implementing any high default value there as it may result in problems for other users.

**Comment by scramjetFoam** [comment]
> Hi,
> 
> pyjac files are generated by the `pyjac2foam.sh` script in which we call ct2foam fitting function
> 
> https://github.com/kahilah/ct2foam/blob/09837b4c0a4a19e02fd21f0a0d0a74cb83285473/pyjac2foam/pyjac2foam.sh#L190
> 
> As you can see, there is no -Th argument prescribing the higher temperature limit as it is typically intended for rather standard cases.
> 
> You can add your own limit there but I'm not a fan implementing any high default value there as it may result in problems for other users.

Roger that. Thank you.

**Comment by scramjetFoam** [comment]
> Hi,
> 
> pyjac files are generated by the `pyjac2foam.sh` script in which we call ct2foam fitting function
> 
> https://github.com/kahilah/ct2foam/blob/09837b4c0a4a19e02fd21f0a0d0a74cb83285473/pyjac2foam/pyjac2foam.sh#L190
> 
> As you can see, there is no -Th argument prescribing the higher temperature limit as it is typically intended for rather standard cases.
> 
> You can add your own limit there but I'm not a fan implementing any high default value there as it may result in problems for other users.

Hi,

I just made the following changes to this suggestion, but it doesn't seem to work.

![截图_20240417130955](https://github.com/kahilah/ct2foam/assets/80505084/8d1a7625-f419-4e16-8764-ce8834bc1336)

![截图_20240417131414](https://github.com/kahilah/ct2foam/assets/80505084/aaf27e50-7e0c-4e9a-82c5-37a77f4745fb)

**Comment by kahilah** [comment]
Hi, sorry for a late respond, but I tested this and it works for me.

what comes to my mind is that you are making the change within the repository and you are not installing this package in developer mode "pip install -e ." so the pyjac2foam script is not actually updated but python picks the old one from package installation directory.

So either
1) reinstall package and rerun again or
2) make your own pyjac2foam script located elsewhere from the repo.

**Comment by kahilah** [comment]
Closing as this should be resolved.
