### ISSUE TITLE
pyjac2foam can delete the whole file system if the run path contains spaces!

### ISSUE THREAD

**Issue by arintanen** [kahilah/ct2foam#9]
If pyjac2foam is ran in a location containing spaces, (e.g.  /home/user1/some folder_with_space/folder1/folder2),
command " rm -rf $lib_path/*" at line number 56 will get translated to "rm -rf  /home/user1/ folder_with_space/folder1/folder2*", which will remove the entire user's home directory (which already happened in our group today).

**Comment by kahilah** [comment]
Having white space caharacters in folder names will cause you plenty of issues in general with linux and shell scripts so the right solution is not to have them.

There are multiple other shell scripts outside ct2foam which can fail so would be really cautious in general. 

It is unfortunate to hear you may have lost some data and I'm open for PR on this topic if you resolve the issue. Basically one should remove ambiguity by introducing "" and escaping of white spaces in correct manner. Or raise an error if white space is detected. However, there can always be edge cases so safer to follow standards and not to have them.

**Comment by arintanen** [comment]
Thanks for your fast reply! I agree that one should not use special characters/white-spaces in file paths and I think these scripts don't need to be fully compatible with such paths. But _rm -rf $VAR/*_ is dangerous so I would suggest to at least add "" around every variable, since sometimes mistakes happen. My coworker was running this tool in his dropbox folder "dropbox (name)", where one could easily forget the presence of white spaces when the path is long.  

I can make a pull request next week.

**Comment by kahilah** [comment]
Sounds good. We could also consider removing the force flag.

**Comment by kahilah** [comment]
Thanks for the PR #10 which makes the standard behavior safer. But please tell your colleague that he will have more problems in the future with other linux packages so better to rename those directories...been there...
